### ISSUE TITLE
i have some problems with my pynlpir

### ISSUE THREAD

**Issue by WayRooney** [tsroten/pynlpir#71] opened 2017-03-25 03:28 UTC
hey tsroten:
    i am a university student from china,these days i was buy with my instructor's project.To accomplish that, i have installed pynlpir on my anaconda3,however,after downloading it successfully, i meet problems when i write simple codes to test it.
    it was like 'self._handle = _dlopen(self._name, mode),TypeError: bad argument type for built-in operation',i would like to know if you have any solutions with that.
    Thanks a lot!

**Comment by yangqinj** [comment] 2017-03-25 03:40
Same problem...

**Comment by tsroten** [comment] 2017-03-25 03:59
@WayRooney @yangqinj Thanks for using PyNLPIR!

Could you please give me more information about your problem.
- What code did you run?
- What was the entire error message?
- What version of Python are you using?
- What operating system are you using?

**Comment by WayRooney** [comment] 2017-03-25 04:04
my code is as follows
import pynlpir
pynlpir.open()
s = '欢迎科研人员、技术工程师、企事业单位与个人参与NLPIR平台的建设工作。'
pynlpir.segment(s)

entire error message:

  File "D:\Anaconda3\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)

TypeError: bad argument type for built-in operation

i am using python3.5 on anaconda3 and mu system is win64

**Comment by tsroten** [comment] 2017-03-25 04:23
This is a duplicate of https://github.com/tsroten/pynlpir/issues/63. Closing this issue.

**Closed by tsroten** 2017-03-25 04:23 UTC

**Comment by tsroten** [comment] 2017-03-25 04:45
@WayRooney @yangqinj This should be fixed. If you could, please test it and let me know.

Run `pip install --upgrade pynlpir` to upgrade PyNLPIR.

**Comment by WayRooney** [comment] 2017-03-25 08:33
Thanks a lot tsroten,it is done and helps me a lot.
if having other questions,i will seek help from you again.
see you!
